title: Manoj Negi
description: Startups Builder, Solution Architect, Laravel Expert, & Consultant.
sub_description: A full stack web developer and consultant based in Delhi, IN. I have 4+ year of experience and I work on Laravel Php Framework, Vue.js, Mysql & Many Others.

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

external-image: true
picture: https://avatars0.githubusercontent.com/u/7446742?v=3&u=00733420e005cc53cf7336848e927578ebc7e1f6&s=400

github: https://github.com/manojnegii90
linkedin: https://www.linkedin.com/in/manoj-negi-52aa3688/
skype: manojnegiii57
email: manojnegiii57@gmail.com
call: +917827388365